---
- name: ensure data directory
  file:
    state: directory
    path: "{{ mongodb_final_config.storage.dbPath }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"

- name: ensure log directory
  file:
    state: directory
    path: "{{ mongodb_final_config.systemLog.path | dirname }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
  when: mongodb_final_config.systemLog.path is defined

- name: write logrotate config
  template:
    src: "{{ mongodb_logrotate_template }}"
    dest: /etc/logrotate.d/mongod
    owner: root
    group: root
    mode: 0644
  when: mongodb_logrotate_enabled and mongodb_logrotate_config
        and mongodb_final_config.systemLog.path is defined and mongodb_final_config.systemLog.path
        and mongodb_final_config.systemLog.destination is defined and mongodb_final_config.systemLog.destination|lower == 'file'

- name: write config file
  template:
    src: "{{ mongodb_config_template }}"
    dest: "{{ mongodb_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mongodb

- name: ensure keyFile directory
  file:
    state: directory
    path: "{{ mongodb_final_config.security.keyFile | dirname }}"
  when: mongodb_keyfile_content
        and mongodb_final_config.security.keyFile is defined
        and mongodb_final_config.security.keyFile

- name: create keyFile
  copy:
    dest: "{{ mongodb_final_config.security.keyFile }}"
    content: "{{ mongodb_keyfile_content }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0600
  when: mongodb_keyfile_content
        and mongodb_final_config.security.keyFile is defined
        and mongodb_final_config.security.keyFile
  notify:
    - restart mongodb

- name: systemd service to disable THP
  template:
    src: disable_thp.service.j2
    dest: /etc/systemd/system/disable-thp.service
    owner: root
    group: root
    mode: 0644
  when: mongodb_disable_thp | bool
  notify:
    - reload systemd
    - restart disable-thp
    - restart mongodb

- name: enable disable-thp service
  systemd:
    name: disable-thp
    enabled: true
  when: mongodb_disable_thp | bool

- name: manage mongod service
  service:
    name: mongod
    state: "{{ mongodb_service_state }}"
    enabled: "{{ mongodb_service_enabled }}"

- name: install pymongo package
  package:
    name: python-pymongo
    state: present
  when: mongodb_pymongo_install_method == 'package'

- name: install pip
  package:
    name: python-pip
    state: present
  when: mongodb_pymongo_install_method == 'pip'

- name: pip install pymongo
  pip:
    name: pymongo
    state: present
  when: mongodb_pymongo_install_method == 'pip'
