---
- name: add yum repository
  yum_repository:
    name: "mongodb-org-{{ mongodb_version[0:3] }}"
    description: MongoDB Repository
    baseurl: "{{ mongodb_repository[mongodb_version[0:1]] }}"
    gpgkey: "{{ 'https://www.mongodb.org/static/pgp/server-' + mongodb_version[0:3] + '.asc' if mongodb_version[0:1] == '3' else omit }}"
    gpgcheck: "{{ 'yes' if mongodb_version[0:1] == '3' else 'no' }}"
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: install mongodb yum package
  yum:
    name: mongodb-org-{{  mongodb_version }}*
    state: present
  notify:
    - restart mongodb
