---
- name: add apt key
  apt_key:
    keyserver: "{{ mongodb_apt_keyserver }}"
    id: "{{ mongodb_apt_key_id }}"

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: add apt repository
  apt_repository:
    filename: mongodb-org-{{ mongodb_version[0:3] }}
    repo: "{{ mongodb_repository[mongodb_version[0:1]] }}"

- name: install mongodb apt package
  apt:
    name: mongodb-org={{ mongodb_version }}*
    state: present
  notify:
    - restart mongodb
