---
- name: add yum repository
  yum_repository:
    name: "mongodb-org-{{ mongodb_version_string[0:3] }}"
    description: MongoDB Repository
    baseurl: "{{ mongodb_repository }}"
    gpgkey: "{{ mongodb_repo_key_url }}"
    gpgcheck: "{{ mongodb_repo_key_url | length > 0 }}"
    enabled: true

- name: install mongodb yum package
  yum:
    name: mongodb-org-{{  mongodb_version_string }}*
    state: present
  notify:
    - restart mongodb
