---
- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: present

- name: add apt key
  apt_key:
    url: "{{ mongodb_repo_key_url }}"
    id: "{{ mongodb_apt_key_id }}"
  when: mongodb_apt_key_id | length

- name: add apt repository
  apt_repository:
    filename: mongodb-org-{{ mongodb_version_string[0:3] }}
    repo: "{{ mongodb_repository }}"

- name: install mongodb apt package
  apt:
    name: mongodb-org={{ mongodb_version_string }}*
    state: present
  notify:
    - restart mongodb
