---
- name: assert supported mongodb_version
  assert:
    that:
      - mongodb_version_string is version('3.0', '>=')
      - mongodb_version_string | length >= 3
      - mongodb_version_string | length <= 5
    msg: mongodb_version must be 3.0 or above in the format of x.y or x.y.z

- name: include OS-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- include: install_{{ ansible_os_family | lower }}.yml

- include: configure.yml

- include: mms_monitoring.yml
  when: mongodb_install_monitor_agent

- include: mms_automation.yml
  when: mongodb_install_automation_agent
