---
- name: assert supported mongodb_version
  assert:
    that:
      - mongodb_version[0:3] == '2.6' or mongodb_version[0:1] == '3'
      - not (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('16.04', '>=') and mongodb_version[0:3] | version_compare('3.2', '<'))

- include_vars: "{{ ansible_os_family | lower }}.yml"

- name: set mongodb configuration
  set_fact:
    mongodb_config: "{{ mongodb_base_config | combine(mongodb_os_config, mongodb_config, recursive=True) }}"

- include: install_{{ ansible_os_family | lower }}.yml
- include: configure.yml

- include: mms_monitoring.yml
  when: mongodb_install_monitor_agent

- include: mms_automation.yml
  when: mongodb_install_automation_agent
