---
- name: download monitoring agent
  get_url:
    url: "{{ mongodb_monitor_agent_pkg_url }}"
    dest: /tmp/{{ mongodb_monitor_agent_pkg_url | basename }}

- name: install monitoring agent (deb)
  apt:
    deb: /tmp/{{ mongodb_monitor_agent_pkg_url | basename }}
  when: ansible_os_family == 'Debian'

- name: install monitoring agent (rpm)
  yum:
    name: /tmp/{{ mongodb_monitor_agent_pkg_url | basename }}
    state: present
  when: ansible_os_family == 'RedHat'

- name: write monitoring agent config
  template:
    src: "{{ mongodb_monitor_agent_template }}"
    dest: /etc/mongodb-mms/monitoring-agent.config
    owner: 'mongodb-mms-agent'
    group: 'mongodb-mms-agent'
    mode: 0600
  notify:
    - restart mongodb-mms-monitoring-agent

- name: manage monitoring agent service
  service:
    name: mongodb-mms-monitoring-agent
    state: "{{ mongodb_enable_monitor_agent_service | bool | ternary('started', 'stopped') }}"
    enabled: "{{ mongodb_enable_monitor_agent_service }}"
