---
- name: reload systemd
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'

- name: restart mongodb
  service:
    name: mongod
    state: restarted
  when: mongodb_service_enabled and mongodb_service_state == 'started' and mongodb_restart_on_update

- name: restart mongodb-mms-monitoring-agent
  service:
    name: mongodb-mms-monitoring-agent
    state: restarted
  when: mongodb_enable_monitor_agent_service

- name: restart mongodb-mms-automation-agent
  service:
    name: mongodb-mms-automation-agent
    state: restarted
  when: mongodb_enable_automation_agent_service

- name: restart disable-thp
  systemd:
    name: disable-thp
    state: restarted
  when: mongodb_disable_thp
